title: Franziska Reiher
logo: /assets/img/profilbild_circle_fr.png
theme: jekyll-theme-minimal
description: "Chemistry and Management Msc @Universität Ulm |Data Science Enthusiast"
LinkedIn: "https://www.linkedin.com/in/franziskareiher"
